-- Data Definition Language
-- ALTER Command

-- ALTER TABLE - DROP COLUMN
ALTER TABLE products
DROP COLUMN description;

-- ALTER TABLE - ADD COLUMN
ALTER TABLE products
ADD COLUMN description VARCHAR(255);

-- ALTER TABLE - MODIFY COLUMN
ALTER TABLE products
MODIFY COLUMN description TEXT;

-- ALTER TABLE - MODIFY COLUMN TO ALLOW NULL VALUES
ALTER TABLE orders
MODIFY COLUMN quantity INT NULL;

-- ALTER TABLE - MODIFY COLUMN TO NOT ALLOW NULL VALUES
ALTER TABLE orders
MODIFY COLUMN quantity INT NOT NULL;

-- ALTER TABLE - MODIFY COLUMN TO HAVE DEFAULT VALUE (INT DEFAUT IS NULL)
ALTER TABLE products
MODIFY COLUMN stock_quantity INT NOT NULL DEFAULT 0;